
target 'SAEvents_Example', :exclusive => true do
  pod 'SAEvents', :path => '../'
  pod 'SAEvents/Moat', :path => '../'
end

target 'SAEvents_Tests', :exclusive => true do
  pod 'SAEvents', :path => '../'
end
