platform :ios, '7.0'

target 'SAEvents_Example' do
    pod 'SAEvents', :path => '../'
    pod 'SAEvents/Moat', :path => '../'
    pod 'SAWebPlayer'
    pod 'SAVideoPlayer'
    
    target 'SAEvents_Tests' do
        inherit! :search_paths
    end 
end
